# NOTE: This Makefile assumes that dependencies are installed and, if a virtual
# environment is used, it is activated.

## Variables ##################################################################
# NOTE: Define any variables here if needed in the future

# Docker image configuration
REGISTRY_NAMESPACE ?= jaeaeich
NAME := poiesis
VERSION := $(shell uv tree | grep ${NAME} | awk '{print $$2}' | sed 's/^v//')
BUILD_DATE := $(shell date -u +'%Y-%m-%dT%H:%M:%SZ')
GIT_REVISION := $(shell git rev-parse HEAD)
PY_VERSION := 3.13.0
DOCKERFILE := deployment/images/Dockerfile

# Full image names
IMAGE_NAME := ${REGISTRY_NAMESPACE}/${NAME}
IMAGE_TAG_LATEST := ${IMAGE_NAME}:latest
IMAGE_TAG_VERSION := ${IMAGE_NAME}:${VERSION}

## Documentation ##############################################################
# NOTE: Keep all the targets in alphabetical order for better readability.

default: help

.PHONY: help
help:
	@echo "\nUsage: make [target] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
	@echo "Available targets:\n"

	@echo "Code Quality ------------------------------------------------------------------"
	@echo "  \033[1m\033[35mformat-lint\033[0m \033[37m(fl)\033[0m: \033[36mRun linter, formatter, spellcheck.\033[0m"
	@echo "  \033[1m\033[35mprecommit-check\033[0m \033[37m(pc)\033[0m: \033[36mRun all pre-commit checks.\033[0m"
	@echo "  \033[1m\033[35msecurity\033[0m \033[37m(s)\033[0m: \033[36mRun security scans.\033[0m"
	@echo "  \033[1m\033[35mtype-check\033[0m \033[37m(tc)\033[0m: \033[36mPerform type checking.\033[0m\n"

	@echo "Deployment --------------------------------------------------------------------"
	@echo "  \033[1m\033[35mbuild-image\033[0m \033[37m(bi)\033[0m: \033[36mBuild container image.\033[0m"
	@echo "  \033[1m\033[35mclean-image\033[0m \033[37m(ci)\033[0m: \033[36mRemove container image.\033[0m"
	@echo "  \033[1m\033[35mget-token-for-alice\033[0m \033[37m(gta)\033[0m: \033[36mGet token for Alice (user from Keycloak).\033[0m\n"

	@echo "Development -------------------------------------------------------------------"
	@echo "  \033[1m\033[35mdev\033[0m \033[37m(d)\033[0m: \033[36mStart Poiesis development server.\033[0m\n"

	@echo "Documentation -----------------------------------------------------------------"
	@echo "  \033[1m\033[35mdocs\033[0m \033[37m(d)\033[0m: \033[36mGenerate project documentation.\033[0m\n"

	@echo "Environment Management --------------------------------------------------------"
	@echo "  \033[1m\033[35mclean-venv\033[0m \033[37m(cv)\033[0m: \033[36mRemove virtual environment.\033[0m"
	@echo "  \033[1m\033[35minstall\033[0m \033[37m(i)\033[0m: \033[36mInstall app and dependencies.\033[0m"
	@echo "  \033[1m\033[35mvenv\033[0m \033[37m(v)\033[0m: \033[36mCreate virtual environment.\033[0m\n"

	@echo "Testing -----------------------------------------------------------------------"
	@echo "  \033[1m\033[35mtest\033[0m \033[37m(t)\033[0m: \033[36mRun all tests.\033[0m\n"

## Autogenerated Targets ######################################################
# NOTE: Keep all the targets in alphabetical order for better readability.
# NOTE: Do not modify the autogenerated targets, unless necessary, write custom
# targets in the custom section below..

.PHONY: clean-venv cv
clean-venv:
	@echo "\nRemoving the virtual environment ++++++++++++++++++++++++++++++++++++++++++++++\n"
	@rm -rf .venv

cv: clean-venv

.PHONY: docs d
docs:
	@echo "\nGenerating project documentation ++++++++++++++++++++++++++++++++++++++++++++++\n"
	@sphinx-apidoc -f -o docs/source/pages poiesis
	@cd docs && make html
	@echo "\nSummary ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
	@echo "Documentation generated successfully."
	@echo "Open docs/build/html/index.html in your browser."
	@echo "Or serve it locally using:"
	@echo "python -m http.server -d docs/build/html/"

d: docs

.PHONY: format-lint fl
format-lint:
	@echo "\nRunning linter and formatter using ruff and typos +++++++++++++++++++++++++++++\n"
	@ruff format && ruff check --fix
	@typos .

fl: format-lint

.PHONY: install i
install:
	@echo "\nInstalling this package its dependencies +++++++++++++++++++++++++++++++++\n"
	@uv sync --all-extras --all-groups

i: install

.PHONY: precommit-check pc
precommit-check:
	@echo "\nRunning pre-commit checks +++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
	@pre-commit run --all-files

pc: precommit-check

.PHONY: security s
security:
	@echo "\nRunning security scans using bandit and safety ++++++++++++++++++++++++++++++++\n"
	@uvx safety check --full-report
	@bandit -c pyproject.toml -r poiesis

s: security

.PHONY: test t
test:
	@echo "\nRunning tests using pytest ++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
	@pytest tests/

t: test

.PHONY: type-check tc
type-check:
	@echo "\nPerforming type checking with pyrefly ++++++++++++++++++++++++++++++++++++++++\n"
	@pyrefly check poiesis

tc: type-check

.PHONY: venv v
venv:
	@echo "\nCreating a virtual environment ++++++++++++++++++++++++++++++++++++++++++++++++\n"
	@uv venv

v: venv

## Custom Targets #############################################################
# NOTE: Keep all the targets in alphabetical order for better readability.
# NOTE: Add any custom targets here if needed in the future.

PHONY: build-docker-image bi
build-docker-image:
	@echo "\nBuilding Docker image +++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
	@docker build \
		--platform linux/amd64,linux/arm64 \
		--build-arg PY_VERSION="${PY_VERSION}" \
		--build-arg BUILD_DATE="${BUILD_DATE}" \
		--build-arg GIT_REVISION="${GIT_REVISION}" \
		--build-arg VERSION="${VERSION}" \
		-t ${IMAGE_TAG_VERSION} \
		-t ${IMAGE_TAG_LATEST} \
		-f ${DOCKERFILE} .
	@echo "\nDocker image built successfully: jaeaeich/poiesis:latest\n"

bi: build-docker-image

.PHONY: clean-docker-image ci
clean-docker-image:
	@echo "\nRemoving Docker image +++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
	@docker rmi ${IMAGE_TAG_LATEST} ${IMAGE_TAG_VERSION} 2>/dev/null || echo "Docker images not found."
	@echo "\nDocker image removed successfully (if it existed).\n"

 ci: clean-docker-image
.PHONY: dev
dev:
	@echo "\nStarting Poiesis development server ++++++++++++++++++++++++++++++++++++++++++++\n"
	@echo "Starting server on http://localhost:8089/ga4gh/tes/v1/ui"
	@uvicorn poiesis.api.app:app --reload --host localhost --port 8089

.PHONY: get-token-for-alice gta
get-token-for-alice:
	@echo "\nGetting a token for Alice ++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
	@bash -c 'response=$$(curl -s -X POST "${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token" \
		-H "Content-Type: application/x-www-form-urlencoded" \
		-d "client_id=${KEYCLOAK_CLIENT_ID}" \
		-d "client_secret=${KEYCLOAK_CLIENT_SECRET}" \
		-d "username=alice" \
		-d "password=password" \
		-d "grant_type=password"); \
		if command -v jq >/dev/null 2>&1 && command -v pbcopy >/dev/null 2>&1; then \
			echo "$$response" | jq -r .access_token | pbcopy; \
			echo "Token copied to clipboard using jq and pbcopy (macOS)"; \
		elif command -v jq >/dev/null 2>&1 && command -v xsel >/dev/null 2>&1; then \
			echo "$$response" | jq -r .access_token | xsel -ib; \
			echo "Token copied to clipboard using jq and xsel (Linux)"; \
		elif command -v jq >/dev/null 2>&1 && command -v xclip >/dev/null 2>&1; then \
			echo "$$response" | jq -r .access_token | xclip -selection clipboard; \
			echo "Token copied to clipboard using jq and xclip (Linux)"; \
		elif command -v grep >/dev/null 2>&1 && command -v sed >/dev/null 2>&1; then \
			token=$$(echo "$$response" | grep -o "\"access_token\":\"[^\"]*\"" | sed "s/\"access_token\":\"//;s/\"//"); \
			echo "Token: $$token"; \
		else \
			echo "Unable to parse token. Raw response:"; \
			echo "$$response"; \
		fi'

gta: get-token-for-alice
