apiVersion: v1
kind: Service
metadata:
  name: {{ include "poiesis.api.componentName" . }}
  labels:
    {{- include "poiesis.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.poiesis.service.type }}
  ports:
    - port: {{ .Values.poiesis.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "poiesis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
{{- if .Values.poiesis.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rules
spec:
  ingressClassName: {{ .Values.poiesis.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.poiesis.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: poiesis-api
            port:
              number: {{ .Values.poiesis.service.port }}
{{- end }}
